### ISSUE TITLE
Create Image Display episode

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#18]
## Definition of done

- Create markdown file for the episode
- Get feedback
- Refine episode content

**Comment by MonikaSvata** [comment]
Steve to review after Dave/David's review, incorporate comments and re-submit to review.

**Comment by thompson318** [comment]
Agreed with Kimberly post meeting that she'd do this as it involves local image files.

**Comment by K-Meech** [comment]
Closing as this episode is merged now
