### ISSUE TITLE
Change Carpentries branding to IDEAS

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#2]
## Definition of Done: 

Change Carpentries logo/branding in lesson template to IDEAS.

**Comment by davecash75** [comment]
Hi @K-Meech -
Can you see these files from the website repository?
* [Style sheet with colours and fonts](https://github.com/HealthBioscienceIDEAS/healthbioscienceideas.github.io/blob/main/assets/css/style.scss)
* [Title logo](https://github.com/HealthBioscienceIDEAS/healthbioscienceideas.github.io/blob/main/images/logo/logo.svg)
* [Brain](https://github.com/HealthBioscienceIDEAS/healthbioscienceideas.github.io/blob/main/images/illustrations/brain_with_tracts_white_bg.png)
Let me know if any other branding issues needed.

**Comment by K-Meech** [comment]
Thanks @davecash75 ! - I can see all those files on the website repository. That should be all we need for branding - but I'll let you know if anything else comes up.

**Comment by MonikaSvata** [comment]
## Definition of Done

Look and feel of IDEAS website.

**Comment by milanmlft** [comment]
@K-Meech I can help with this if needed. The styling of the Carpentries lessons is handled by the [*varnish* package](https://github.com/carpentries/varnish).

For the **L2D* project, we created a [fork](https://github.com/LearnToDiscover/varnish) to add custom logos and colors. You can see an example here: https://learntodiscover.github.io/Basic_Python

**Comment by K-Meech** [comment]
Thanks @milanmlft ! That would be great - a similar fork with IDEAS branding sounds like a good solution.

**Comment by milanmlft** [comment]
Interesting, the IDEAS logo gets shown on the "Introduction" episode, but not on the homepage of the [course website](https://healthbioscienceideas.github.io/microscopy-novice/)... So reopining this issue 😅 
Will investigate!

**Comment by milanmlft** [comment]
Never mind, it was just a matter of clearing the cache! (by default, sandpaper will only rebuild files that have changed, so it was still using the old index/home page file from before the rebranding), but should be fixed now
