### ISSUE TITLE
Evaluate napari plugins for basic image processing

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#24]
For day 2, we'll need Napari plugins that can do basic operations like: image histograms, gaussian blur, thresholding, connected components, opening/closing

Some options to try out: 
- [napari-segment-blobs-and-things-with-membranes](https://www.napari-hub.org/plugins/napari-segment-blobs-and-things-with-membranes) (scikit-image based)
- [napari-simpleitk-image-processing](https://www.napari-hub.org/plugins/napari-simpleitk-image-processing) (itk based)
- [napari-zelda](https://www.napari-hub.org/plugins/napari-zelda)
- [napari-matplotlib](https://www.napari-hub.org/plugins/napari-matplotlib) (for image histograms)
- [napari-brightness-contrast](https://www.napari-hub.org/plugins/napari-brightness-contrast) (for image histograms)

## Definition of done
- [ ] plugins cover the required basic operations
- [ ] Easy to install and use (e.g., on M1/2 chips)
- [ ] Histograms ideally work well for 2D/3D + RGB images

**Comment by p-j-smith** [comment]
I've had a look at some of the plugins and have some thoughts:

### [napari-zelda](https://www.napari-hub.org/plugins/napari-zelda)

- Is not yet tested on Python 3.10+ (as [one of its dependencies has only just added support for it](https://github.com/h2oai/datatable/pull/3484))
- Has some pre-defined workflows that could be useful, but they are not the most intuitive or straightforward to use

### [napari-allencell-segmenter](https://www.napari-hub.org/plugins/napari-allencell-segmenter)

- developed by the same team that make `napari-aicsimageio`
- easy to install, but only supports single 3D images (no timeseries)

### [napari-partseg](https://www.napari-hub.org/plugins/PartSeg)

- easy to install
- lots of tools for segmentation and calculating statistics; some tools have lots of parameters that can be set (which is probably useful but perhaps overwhelming for students on the course)
- no support for timeseries

### [napari-segment-blobs-and-things-with-membranes](https://www.napari-hub.org/plugins/napari-segment-blobs-and-things-with-membranes)

- Has a large suite of tools for doing the sorts of operations we're interested in (Gaussian blur, thresholding, etc.)
- Easy to install using pip (although I don't have an M1 Mac so can't test that out):
```bash
python -m pip install napari-segment-blobs-and-things-with-membranes
```
- Actually provides a long list of plugins (available via `Plugins > napari-segment-blobs-and-things-with-membranes > <plugin list>`)

- Using some of napari's builtin data (`File > Open sample > napari builtins > Human mitosis`), can label cells using the following workflow (each step is the name a separate plugin from the above list):

```
gaussian blur
threshold otsu
split touching objects
connected component labelling
manually split labels / manually merge labels
```

### [napari-simpleitk-image-processing](https://www.napari-hub.org/plugins/napari-simpleitk-image-processing)

- Similar to `napari-segment-blobs-and-things-with-membranes` - has a large suite of tools for doing the sorts of operations we're interested in
- Easy to install using pip:
```bash
python -m pip install napari-simpleitk-image-processing 
```
- this also provides a long list of plugins (available via `Plugins > napari-simpleitk-image-processing > <plugin list>`)

- Using the same builtin data (`Human mitosis`), can label cells and calculate statistics using the following workflow (again each step is the name a separate plugin from the above list):

```
gaussian blur
theshold otsu
connected component labelling
label statistics
```

### Summary

`napari-segment-blobs-and-things-with-membranes` and `napari-simpleitk-image-processing` are the most promising in terms of being easy to use and having the functionality we need.

In differences between the two:
- `napari-segment-blobs-and-things-with-membranes` has a tool to split touching objects before the segmentation step, and another to manually relabel data
- `napari-simpleitk-image-processing` can calculate some simple cell statistics. Plus, the connected component labelling seems to perform slightly better compared to `napari-segment-blobs-and-things-with-membranes` (with fewer neighbouring cells being incorrectly connected)

So we might want to use both `napari-segment-blobs-and-things-with-membranes` and `napari-simpleitk-image-processing`?

**Comment by K-Meech** [comment]
Thanks @p-j-smith - this is a great overview! Seems like `napari-segment-blobs-and-things-with-membranes` and `napari-simpleitk-image-processing` should cover everything we need for day 2.

**Comment by K-Meech** [comment]
I'll close this issue now, as all episodes that use these napari plugins are merged
