### ISSUE TITLE
Update Episode Timing based initial teaching

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#28]
Each episode should have an estimate of the teaching time + exercise time at the top e.g.
```
---
title: 'Imaging Software'
teaching: 30
exercises: 10
---
```

### Definition of done

- All episodes have timing estimates
- These are consistent / good first estimates that can then be refined in the test runs of the course

**Comment by MonikaSvata** [comment]
@dpshelio , @davecash75 to find audience for the first trial teaching of this course (probably a single day)

@K-Meech @thompson318 to teach this first trial course. 
@K-Meech to trial initial course with Dave.
@K-Meech and @thompson318 to give their availability.

**Comment by MonikaSvata** [comment]
Dave to send out the 'Choosing Acquisition Setting' episode for feedback.
