### ISSUE TITLE
Episode for additional resources

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#29]
### Definition of done

- Add an episode at the end of the course with useful additional resources + links

**Comment by K-Meech** [comment]
Some useful resources:
- Pete Bankhead's bioimage book: https://bioimagebook.github.io/
- Bioimaging guide: https://www.bioimagingguide.org
- Data Carpentry: Image Processing with Python: https://datacarpentry.org/image-processing/
- UCL Bioimage interest group: https://www.ucl.ac.uk/lmcb/ucl-biig
- Eurobioimaging talks? https://www.eurobioimaging.eu/about-us/virtual-pub
- Would be good to link to some of Robert Haase's tutorials - he has talks on youtube + published talk slides on Napari
- Royal society technical teabreaks? https://www.youtube.com/playlist?list=PLoemaChWEBWHINjLnWFIFOZKTE13mm3ac

**Comment by MonikaSvata** [comment]
In progress

**Comment by MonikaSvata** [comment]
Dave to review and merge if happy.
