### ISSUE TITLE
Define the list of pre-requisites and add them to the lesson

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#3]
## Definition of Done

Fill out ```index.md``` by:
- Adding an overall description of the lesson
- Define the list of pre-requisites and required knowledge of Python and microscopy. 
- Adding a list of prerequisites (e.g. any python or microscopy knowledge required)

Example from another carpentries course: https://github.com/swcarpentry/python-novice-gapminder/blob/main/index.md

**Comment by K-Meech** [comment]
Here's a rough first draft of an overall description of the lesson + prerequisites. The description is adapted from the workshop notes - we can expand it with information about the content of each day once that is finalised. The prerequisities are also very minimal, as we are keeping it as coding light as possible + aiming at microscopy novices. 

## Lesson description

This lesson provides an overview of the fundamentals of imaging data that has been acquired through light microscopy experiments. This course is aimed at all researchers who are looking to work with light microscopy imaging data, or to refresh their knowledge on some of the key fundamentals.  

## Prerequisites
- Some prior experience with acquiring/working with light microscopy data would be useful, but isn't necessary. This course is aimed at anyone who is looking to work with light microscopy imaging data in their research projects.
- This course will use some Python tools, but no prior experience is necessary.

**Comment by K-Meech** [comment]
I updated the prerequisites based on our meeting - are you happy with the wording below @davecash75 ?

## Lesson description

This lesson provides an overview of the fundamentals of imaging data that has been acquired through light microscopy experiments. This course is aimed at all researchers who are looking to work with light microscopy imaging data, or to refresh their knowledge on some of the key fundamentals.  

## Prerequisites
- Some prior experience with acquiring/working with light microscopy data would be useful, but isn't necessary. This course is aimed at anyone who is looking to work with light microscopy imaging data in their research projects.
- No python experience is necessary or assumed, but you will get more out of the course if you know some basics e.g. from the [Software Carpentry python course](https://swcarpentry.github.io/python-novice-inflammation/)
- Please bring a laptop (Windows, Mac or Linux) and follow the setup instructions before the start of the course

**Comment by davecash75** [comment]
Great. Very minor suggestion to last billet point. 
 Please bring a laptop (Windows, Mac or Linux) to the lesson. Before the start of the course, please follow the setup instructions so that your laptop is ready to run the material in the lessons

**Comment by davecash75** [comment]
@K-Meech Now this is more less agreed, does this need a pull request to add these into the website?

**Comment by K-Meech** [comment]
Thanks @davecash75 ! - I'll go ahead and make a PR to add this to the ```index.md``` file

**Comment by MonikaSvata** [comment]
David PS to provide link to the next UCL software Carpentries course link - so that we can advertise and point people to it as a potential pre-requisite of the course.
