### ISSUE TITLE
Create Quality Control and Manual Segmentation episode

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#36]
## Definition of done
- Create markdown file for the episode
- Get feedback
- Refine episode content

**Comment by K-Meech** [comment]
@thompson318 - just linking this issue: https://github.com/HealthBioscienceIDEAS/microscopy-novice/issues/24 in case you haven't seen it. We looked at different plugins to use for the three segmentation/processing episodes and decided `napari-segment-blobs-and-things-with-membranes` and `napari-simpleitk-image-processing`  were the best fit.

**Comment by MonikaSvata** [comment]
Approved by Stephen. Waiting for Dave's approval.
