### ISSUE TITLE
Collect example data

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#5]
## Definition of Done

Collect example data for the different episodes e.g.

- Small (fast to download) images to show different image types - 2D / 3D / multichannel / RGB / time series. 
- A clean dataset for a cell counting exercise
- A messier/more realistic dataset for cell counting
- A larger dataset for the long-form example on the final day e.g. histopathology data on omero

- Testing is not a part of Definition of Done of this task (data will be tested along with lessons).

Smaller datasets could be placed directly in the repo or uploaded to Figshare / Zenodo for download e.g. the data carpentry image processing lesson stores example data in [figshare](https://figshare.com/articles/dataset/Data_Carpentry_Image_Processing_Data_beta_/19260677)

**Comment by K-Meech** [comment]
I looked through the example data that comes with napari. These images can easily be loaded via the user interface using File > Open Sample... They are the same example images as scikit-image's [data](https://scikit-image.org/docs/stable/api/skimage.data.html)

The most relevant ones are:
- Human mitosis (2D grayscale)
- Cells (3D + 2Ch) - 3D fluorescence microscopy data with 2 channels
- Kidney (3D + 3Ch) - 3D fluorescence microscopy data with 3 channels
- Skin (RGB) - 2D hematoxylin + eosin stained slide
- Immunohistochemistry (RGB) - 2D IHC staining with hematoxylin counterstaining

Some quick screenshots:
![Screenshot 2023-11-03 145850](https://github.com/HealthBioscienceIDEAS/microscopy-novice/assets/24316371/84c434d8-a281-4c51-9828-a365bdee82ef)

**Comment by davecash75** [comment]
HI @K-Meech what formats are these in? Or are they directly loaded into napari using the skimage commands?

**Comment by K-Meech** [comment]
@davecash75 These are loaded directly into napari via the user interface (which I believe uses skimage commands in the background) - so they just appear as numpy arrays, rather than images in specific file formats. These are nice for showing imaging basics, but we'd need other examples to show real metadata + file formats. We could consider looking on BioImage Archive if we needed more example data from real experiments: https://www.ebi.ac.uk/bioimage-archive/

**Comment by K-Meech** [comment]
QuPath has some small example pathology images available for download: https://qupath.readthedocs.io/en/stable/docs/intro/acknowledgements.html

**Comment by davecash75** [comment]
What about Omero's sample data: https://downloads.openmicroscopy.org/images/

**Comment by p-j-smith** [comment]
Here's another list of potential resources: https://github.com/AllenCellModeling/aicsimageio/discussions/544#discussioncomment-7568092

**Comment by MonikaSvata** [comment]
Waiting for Nick to send example data.

**Comment by davecash75** [comment]
Nic has sent some over and @K-Meech has access.

**Comment by MonikaSvata** [comment]
Dave to get back to Nic requesting more info about the data.

**Comment by davecash75** [comment]
One thing that is a bit unfortunate @K-Meech @drmatthews @dpshelio is that when I tried opening up the Zeiss CZI file that Nic provided (about 400MB), I get some GL_TEXTURE warnings saying the data size is bigger than the GL Texture mapping limits on my laptop (16484) and there is some downsampling performed. However, Fiji opens this file up with no problem and lots more extensive support and options on how to import this data. On the other hand, I didn't know what half of these options mean - I would expect I would need an episode on what that one dialog box itself means. Much less how to navigate the images in Fiji

**Comment by MonikaSvata** [comment]
Decision made to used one of the Napari images. 

@K-Meech to add notes about limitations - after this it can be closed.

**Comment by K-Meech** [comment]
I added a note about the file size limitations of napari-aicsimageio to the 'filetypes and metadata' episode. I'll close this issue now.
