### ISSUE TITLE
Insert a lesson title

### ISSUE THREAD

**Issue by davecash75** [HealthBioscienceIDEAS/microscopy-novice#52]
@K-Meech @dpshelio  Am I right in thinking where it says "Lesson Title" in the upper left portion of the webpage that this is where we should put the name of the course - something like "Introduction to analysis of microscopy imaging data". It just seems like we should have an overall title to the workshop somewhere...

**Comment by K-Meech** [comment]
Yes - thanks @davecash75 ! I'll make a quick PR to add this
