### ISSUE TITLE
Erosion in 'instance segmentation and measurements' episode

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#60]
My PR was recently merged on `napari-segment-blobs-and-things-with-membranes` to [add more erosion/dilation/opening/closing operations](https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes/pull/33). Using `Tools > Segmentation post-processing > Binary erosion` now allows us to erode segmentations, which wasn't previously possible via the Napari ui.

We could consider updating the final episode to use the napari assistant, as this is now possible. Otherwise, we should at least update the episode text [such as here](https://github.com/HealthBioscienceIDEAS/microscopy-novice/blob/main/episodes/instance-segmentation-and-measurements.md?plain=1#L288), to reflect this change

**Comment by thompson318** [comment]
Fixed with #62.
