### ISSUE TITLE
Decide on python/napari teaching style

### ISSUE THREAD

**Issue by K-Meech** [HealthBioscienceIDEAS/microscopy-novice#7]
## Definition of done

We need to decide how much we focus on directly manipulating images with python (numpy / scikit-image) vs only using the napari user interface + plugins. We could:

- Use the napari [bundled app](https://napari.org/stable/tutorials/fundamentals/installation.html#prerequisites-for-installing-napari-as-a-bundled-app), install plugins via app + do everything via the GUI (easy installation, but no python access)
- Use Jupyter notebooks, install napari + plugins via conda/python + mostly use plugins for analysis
- Use Jupyter notebooks, install napari + plugins via conda/python + mostly use numpy/scikit-image for analysis, with napari for visualisation

Another combination?
- Install napari + plugins via conda/python; Intro to images (numpy/Napari), Visualisation with Napari (GUI pixel values, ...), and a mix of Jupyter for data analysis from saved data (rather than direct interaction with Napari from Jupyter).

**Comment by davecash75** [comment]
@K-Meech If helpful, here are some previous attempts around talking about images:
https://github.com/HealthBioscienceIDEAS/software_carpentry_september_2022/tree/main
A few different branches are ahead of this one and might be relevant.

**Comment by davecash75** [comment]
Given that we already have the heavy documentation on sandpaper, this seems like a really nice approach to me.

**Comment by K-Meech** [comment]
I'm going to close this issue, as we've decided on using Napari directly + doing any python calls in its built-in console
